### ISSUE TITLE
Autopkg autopromotion option for a specific day, rather than an amount of days

### ISSUE THREAD

**Issue by erikng** [Gusto/it-cpe-opensource#3]
Getting users accustomed to a specific patch day can be beneficial for multiple reasons
- Predictable pattern and user expectations
- Predictable network status
- Predictable CPE fleet status

It would be awesome if we could say "promote packages after x amount of days on Wednesday".  If something was important enough, we would out of band/manually promote something (like a CVE with a forced install).

**Comment by ChefAustin** [comment]
My org would benefit from this as well. 🚎

**Comment by ChefAustin** [comment]
@williamtheaker / @w0de - FWIW, I think this can be closed as PR #28 fulfilled this feature request.
