### ISSUE TITLE
Feature Request (cpe_anyconnect): Allow for `cpe_remote`-based installation of AnyConnect client

### ISSUE THREAD

**Issue by ChefAustin** [Gusto/it-cpe-opensource#38]
I think it would be great if `cpe_anyconnect` had cross-platform `install`/`uninstall` resource actions which were built atop `cpe_remote`. This would allow for consumers of this cookbook to leverage their CDN (as well as make the code a "fully-featured API cookbook", at least in my definition of the term).

My team might have cycles in the coming months to implement this functionality but I felt it prudent to get this feature request submitted in case someone else in the community has the time to implement it (or, perhaps, already has a fork with this feature written).

**Comment by w0de** [comment]
Yes, I think that is possible. I'll use cpe_workspaceone's pattern of implementing this (ie: `install` bool attribute, `pkg` hash attribute).

AnyConnect's predeploy package has several components (umbrella, posture, et al) and an install choices array. Supporting that cleanly might be a challenge!

**Comment by w0de** [comment]
Implemented at https://github.com/uber/client-platform-engineering/tree/main/chef/cookbooks/cpe_anyconnect 

Still hoping to add to this version 🌵

**Comment by williamtheaker** [comment]
We dropped Anyconnect, sorry WONTFIX
