### ISSUE TITLE
Repo not populated 

### ISSUE THREAD

**Issue by jalsaman** [Gusto/it-cpe-opensource#74]
The actions run successfully
Currently there is only one recipe Firefox.munki that needs to run.
The Munki repo is totally empty
is there anyway to trace why the repo wasn't populated with the required manifests, pkg and catalogs

**Comment by jalsaman** [comment]
Managed to get it running a few changes have to be done the script doesn't work as copy paste.

**Comment by williamtheaker** [comment]
I'm sorry for missing this issue, but glad to hear you got it working.
